# Generated by Django 4.2.2 on 2024-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collecjv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamecompany",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
