# Generated by Django 4.2.2 on 2023-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collecjv", "0002_alter_game_company_alter_game_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="company",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="models",
                through="collecjv.GameCompany",
                to="collecjv.company",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="state",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="models",
                through="collecjv.GameCollection",
                to="collecjv.collection",
            ),
        ),
    ]
