# Generated by Django 4.2.2 on 2023-08-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collecjv", "0004_alter_company_developer_alter_company_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="collecjv.platform",
            ),
        ),
    ]
