# Generated by Django 4.2.2 on 2023-10-01 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collecjv", "0005_alter_game_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamecompany",
            name="company",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collecjv.company",
            ),
        ),
        migrations.AlterField(
            model_name="gamecompany",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="gamecompany",
            name="game",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collecjv.game",
            ),
        ),
    ]
